"""add user role

Revision ID: 3f59cfd76944
Revises: d5c401399b7a
Create Date: 2026-08-16 20:23:01.159547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f59cfd76944'
down_revision: Union[str, Sequence[str], None] = 'd5c401399b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum(
        'USER',
        'ADMIN',
        name='userrole',
    )

    user_role.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            user_role,
            nullable=False,
            server_default='USER',
        ),
    )

    op.alter_column(
        'users',
        'role',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### 
    op.drop_column('users', 'role')

    user_role = sa.Enum(
        'USER',
        'ADMIN',
        name='userrole',
    )

    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
