"""add_index_to_posts_author_id

Revision ID: 60a2ac98606c
Revises: 74f2e1132212
Create Date: 2026-08-08 15:15:00.280324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a2ac98606c'
down_revision: Union[str, Sequence[str], None] = '74f2e1132212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    # ### end Alembic commands ###
