"""add post listing index

Revision ID: 7c19ebbc540c
Revises: 3f59cfd76944
Create Date: 2026-08-19 10:41:55.656323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c19ebbc540c'
down_revision: Union[str, Sequence[str], None] = '3f59cfd76944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_author_created_id', 'posts', ['author_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_author_created_id', table_name='posts')
    # ### end Alembic commands ###
