"""add username constraint

Revision ID: f78328cb344d
Revises: 7c19ebbc540c
Create Date: 2026-08-19 11:19:10.104077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78328cb344d'
down_revision: Union[str, Sequence[str], None] = '7c19ebbc540c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    def upgrade() -> None:
        op.create_check_constraint(
            "ck_users_username_min_length",
            "users",
            "length(trim(username)) >= 3",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    def downgrade() -> None:
        op.drop_constraint(
            "ck_users_username_min_length",
            "users",
            type_="check",
        )

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
